### ISSUE TITLE
Support converting test cases between atest and postman

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#101]
We could add a new sub-command. Such as: `atest convert --from postman --input example.json --to atest --output example.yaml`.

In the future, we could consider supporting converting between any kind of data. And the `atest` format will play the middle role. It means `A` could to be converted to `atest`, then convert `atest` to your desired format.

## References
* [Postman examples](https://github.com/postmanlabs/newman/blob/89941554304362d0cfec2914d134f738348b27c5/examples/sample-collection.json)
* [JSON schema](https://schema.getpostman.com/json/collection/v2.1.0/collection.json)

**Comment by SamYSF** [comment]
老师您好，我想通过参与一些Issue来了解本项目，我注意到项目中好像已经实现了postman的JSON转换为atest期望的格式，但是部分JSON格式似乎不能成功转换，这个Issue的目的是为了继续完善JSON的转换吗？

**Comment by LinuxSuRen** [comment]
您好，可以继续完善，并且可以试试是否可以进行互转。方便用户对不同的工具做交叉体验。

**Comment by SamYSF** [comment]
谢谢老师的回复，我注意到您的open-source-best-practice中提到"一个 PR 只能包含一类修改"，目前我在转换 postman 格式中我发现了一个无法转换 postman 子文件夹中的测试的问题，我应该将 PR 提到这个 issue 下吗？还是说重新建一个 issue 来说明这个 bug？接下来我想对 postman 请求的 body 转换进行完善，类似这样完善的 PR 都提到这个 issue 下吗？

**Comment by LinuxSuRen** [comment]
很高兴听到您同时还是我的读者。首先来说是否能归到一类，这个没有一个严格的标准，甚至可能是仁者见仁的情况，不同的项目维护者也许考虑的不一样。但是，如果你有自己的理由就是非常好的前提。而且，想您现在这样通过 issue 和维护者沟通好再动手也是比较好的做法，避免浪费精力。

对于当前这个问题，我觉得您可以提一个 PR 来解决您提到的那两个问题，并且关联到这个 issue。
