### ISSUE TITLE
Support loading test cases from git repository

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#103]
Expected usage: `atest run -p https://github.com/LinuxSuRen/api-testing/tree/master/sample --auth personal-token`

We need to consider the git branch and auth. Usually, the branch name could found from the URL. We could manipulate the git repository via [jenkins-x/go-scm](https://github.com/jenkins-x/go-scm).

## UI
In many cases, people will deploy a private Gitlab, and provide it to the team. Having an oauth integration might be a good idea for the users. They could login with their own account. So, we don't need to consider the user management.

See also the similar issue https://github.com/LinuxSuRen/api-testing/issues/94

**Comment by cestlive** [comment]
Read raw data from a git respository and unmarshall the raw content into Suits ?

**Comment by LinuxSuRen** [comment]
> Read raw data from a git respository and unmarshall the raw content into Suits ?

Yes, I'm thinking about making a git repository as the storage backend. So, we don't have a central storage. And users could choose a private git repository to store their test cases. For example, store them into a private Gitlab.

**Comment by cestlive** [comment]
> > Read raw data from a git respository and unmarshall the raw content into Suits ?
> 
> Yes, I'm thinking about making a git repository as the storage backend. So, we don't have a central storage. And users could choose a private git repository to store their test cases. For example, store them into a private Gitlab.



Get it. Let me try to create a pr to handle it

**Comment by LinuxSuRen** [comment]
> Get it. Let me try to create a pr to handle it

Sure. I'm looking forward it.

**Comment by cestlive** [comment]
> In many cases,

I have a question:

atest run -p https://github.com/LinuxSuRen/api-testing/tree/master/sample

the `[pattern ](https://github.com/LinuxSuRen/api-testing/tree/master/sample)` will point to a specific yaml file or a directory?

**Comment by LinuxSuRen** [comment]
In my view, some basic information of a git repo are necessary. Such as: repo URL, branch name, directory. For a private git repository, the auth is required as well.

**Comment by LinuxSuRen** [comment]
hi @cestlive , you can create a new extension with the git feature. See also the existing ones:

https://github.com/LinuxSuRen/api-testing/tree/master/extensions

**Comment by LinuxSuRen** [comment]
[go-git/go-git](https://github.com/go-git/go-git) is a good candidate too. For the extension part, developers could get the connection information from the following code:

https://github.com/LinuxSuRen/api-testing/blob/1e45dd165dc7c6e5bd21ab32d31a612e5da63715/extensions/store-orm/main.go#L85

**Comment by LinuxSuRen** [comment]
Another solution is that making git repository as a SQL server. Such as: [dolthub/dolt](https://github.com/dolthub/dolt).

**Comment by LinuxSuRen** [comment]
hi @cestlive , I'm going to take over this due to no active response in 3 month. Feel free to join me if you're still intested in it.
