### ISSUE TITLE
Support start the proxy server on UI

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#114]
Postman has a wonderful feature that could start an HTTP proxy server. This project already has [the backend function](https://github.com/LinuxSuRen/api-testing/tree/master/extensions/collector). We just need to expose the service on the UI.

See also 

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/ae65a052-a31b-40c4-9e57-fc97c773aff0)

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/c5ee950d-073e-47b1-a077-4e1ece573b78)

**Comment by hahahashen** [comment]
您好，后端代码链接已经失效，https://blog.csdn.net/qq_28284093/article/details/80162842 我通过这篇博客了解到了postman代理设置的功能，我理解，这个issue需要根据后端代码来实现前端页面，来拿到代理对应的配置参数，并从后端拿到请求返回的结果或者cookie展示给用户（根据用户设置），不知道理解是否有错误呢？

**Comment by LinuxSuRen** [comment]
最新的链接 https://github.com/LinuxSuRen/atest-ext-collector

上面时候段代码，实现了基础的代理功能。但，这还是一个独立的二进制文件。我设想的时，提供一个 API 可以下载这个代理程序并启动，而且提供相关的管理功能，例如：查看经过代理的请求、响应等。

**Comment by hahahashen** [comment]
所以这个issue是想要在前端提供一个页面，该页面上有一个下载链接，点击链接即可下载获取程序。
提供相关的管理功能这个功能，是需要代理与api-testing进行交互？

**Comment by LinuxSuRen** [comment]
是提供代理的使用、管理功能，包括：
* 启动、关闭代理服务（不需要用户下载）
* 查看代理服务收到的流量
* 从代理收到的流量信息中提取测试用例

当然，当前 issue 只要实现第一步即可。

我稍微解释下为什么需要这个代理。当用户的浏览器指向代理后，用户只要访问目标测试系统（平台）地址，我们的代理服务就会自动记录相关的请求、响应信息，进而根据这个信息来提取、生成测试用例（的基本信息）。这样的目的是减轻创建测试用例的工作量。

甚至，当这个服务成熟之后还可以考虑进一步的流量回放的方式来对系统进行回归测试。
