### ISSUE TITLE
Add step-by-step introductions for the UI

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#115]
The step-by-step introductions are very friendly for the newcomers. We could provide the introductions for the basic functions.

## References
* https://introjs.com/docs/

**Comment by hahahashen** [comment]
您好 该链接https://introjs.com/docs/已经失效，但我理解这个issue是想要向刚了解到这个项目的朋友介绍怎样构建这个项目？或者是给这个项目写一个使用指南？例如：点击某个按钮将会得到怎样的效果，一步步地创建一个测试用例？
并且这个介绍还需要添加在项目前端页面上？或者是readme文档上就可以满足这个需求呢

**Comment by hahahashen** [comment]
您好 该链接 https://introjs.com/docs/ 已经失效，但我理解这个issue是想要向刚了解到这个项目的朋友介绍怎样构建这个项目？或者是给这个项目写一个使用指南？例如：点击某个按钮将会得到怎样的效果，一步步地创建一个测试用例？
并且这个介绍还需要添加在项目前端页面上？或者是readme文档上就可以满足这个需求呢

**Comment by LinuxSuRen** [comment]
这个链接没问题呀，是不是因为你的梯子设置问题。

我设想是就想首次玩一个游戏时，通常会有一个引导教程帮助用户熟悉系统功能。最好的工具、系统应该是不需要有很复杂的文档，尤其是基本功能。
