### ISSUE TITLE
Support GraphQL testCase

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#208]
GraphQL is also a popular API spec. It would be good to support it.

## Adoption
See the GraphQL users:

* https://docs.github.com/en/graphql
* https://docs.gitlab.com/ee/api/graphql/index.html
* https://graphql.org/users/

## References
* https://graphql.org/learn/

**Comment by LinuxSuRen** [comment]
hi @kuv2707 , I see you're learning GraphQL on your GitHub profile. Are you interested in this issue?

**Comment by kuv2707** [comment]
@LinuxSuRen I would love to.
But my current engagements wouldn't allow me to dedicate much time for it, so it might take a while.
If that is fine with you, I would like to contribute.

**Comment by LinuxSuRen** [comment]
That's totally OK for me. I'm using this project in my work. Currently, we haven't adapted it yet. I just did some research about it.

**Comment by kuv2707** [comment]
@LinuxSuRen It appears that I cannot procure the time to work on this issue anytime soon because of my other commitments. It would be a good idea to assign this issue to someone else willing to work on it.

**Comment by LinuxSuRen** [comment]
@kuv2707 No worries. I hope this project could help you someday. And thanks for your effort again.

**Comment by LinuxSuRen** [comment]
Already support in the backend by #326
