### ISSUE TITLE
Docs: Readme file link is 404

### ISSUE THREAD

**Issue by yuluo-yx** [LinuxSuRen/api-testing#255]
![image](https://github.com/LinuxSuRen/api-testing/assets/77964041/8cd2ae7e-dca9-4794-832e-d7385ff29794)

https://github.com/LinuxSuRen/api-testing/blob/master/sample/kubernetes/manifest.yaml

**Comment by LinuxSuRen** [comment]
hi @yuluo-yx , thanks for pointing it. The correct link should be https://github.com/LinuxSuRen/api-testing/blob/master/docs/manifests/kubernetes/default/manifest.yaml

Please feel free to fix it if you are interested in.

**Comment by yuluo-yx** [comment]
> hi @yuluo-yx , thanks for pointing it. The correct link should be https://github.com/LinuxSuRen/api-testing/blob/master/docs/manifests/kubernetes/default/manifest.yaml
> 
> Please feel free to fix it if you are interested in.

okay, I will try fix it.🫡

**Comment by yuluo-yx** [comment]
The issue is solved, close now.
