### ISSUE TITLE
Support set different image registry server

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#259]
This project publishes images to the following container registries:

* docker.io
* ghcr.io

And, the following is kind of the proxy image address. So `linuxsuren.docker.scarf.sh` is an available container registry as well.

`linuxsuren.docker.scarf.sh/linuxsuren/api-testing`

You could add it to the following section

https://github.com/LinuxSuRen/api-testing/blob/dd7cd4634e19623815790a2b63bd4289b18dd586/helm/api-testing/values.yaml#L7

## Expect
Users could use the following flags to choose different container registry:

```shell
helm install atest oci://docker.io/linuxsuren/api-testing \
    --version image.registry=ghcr.io
```

**Comment by WVenus** [comment]
Hi @LinuxSuRen  
Let me try, assigned to me.
