### ISSUE TITLE
Support the execution records

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#345]
> 这是开源之夏 2024 中的题目，如果您对该题目感兴趣并符合[开源之夏对学生的要求](https://summer-ospp.ac.cn/help/student/)，先不要着急动手，请遵守开源之夏官方的时间线以及其他规定。谢谢！

支持用户在 Web 界面上操作时，保留每次接口测试的请求以及响应信息。该功能包括前后端部分，后端部分需要至少包含一种后端存储（例如：[MySQL](https://github.com/LinuxSuRen/atest-ext-store-orm)、KV等）。其他方面的要求：

* 后端单测覆盖率 80+%
* 后端集成测试
* 用户可以从前端看到执行历史记录（默认限制数量为 50 条）
* 考虑如何兼容不同协议（restFul、gRPC）的 Request 和 Response
* 支持把执行记录转为 `curl` 命令
* 相关的必要文档

## 建议
* 完成一些 [Good first issue](https://github.com/LinuxSuRen/api-testing/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) 有助于您更好地从代码层面了解这个项目。这个不会作为选择潜在学生的硬性要求。
* 调研同类产品，了解不同产品的优缺点
* 在官方规定的 Proposal 提交截止时间之前通过邮件（linuxsuren at gmail）预约腾讯会议（或类似工具）进行沟通

## 为什么要选择这个题目
* 您对 Web 开发感兴趣，尤其是不反感同时进行前、后端开发（个人观点：开发者不应该把自己局限到某个语言上，而是发现、解决问题本身上，而开发语言只是一个偏好而已）
* 您对开发工具感兴趣，之后可能会做和接口开发有关系的工作（也就是可能会持续使用该工具）
* 作者本人对开源非常有热情，之前有作为 GSoC、[开源之夏](https://summer-ospp.ac.cn/2021/#/org/prodetail/210030123)、[GLCC](https://github.com/LinuxSuRen/api-testing/issues?q=is%3Aissue+label%3Aglcc+is%3Aclosed) mentor 的经验
* 作者本人对代码、文档的质量要求相对比较高
* 活动期间会组织在线会议（协商周期）进行交流沟通，并把会议录屏上传哔哩哔哩

## 其他
下面是方便大家开发、测试用的一个 Demo 项目。项目采用 SpringBoot 开发，提供了一些用于测试的 APIs：

* https://github.com/devops-ws/learn-springboot
* [项目以及当前议题的视频介绍](https://www.bilibili.com/video/BV1BT421C7yY)

**Comment by 11days** [comment]
1）MySQL：跟了黑马的100个视频，到索引调优之前，不过忘得差不多了；跟了必知必会的代码；看了点实战45讲
2）KV：没有做过Tiny KV，grpc等项目
刚做了webserver，大二，可以参加吗，想法是，大二暑期，实习或者项目二选一

**Comment by 11days** [comment]
这个不是很清楚，大概率是不可以的，根据之前和群友的讨论。。。有人在Windows跑了，前提是用了双系统或者WSL，才能跑，所以这个项目应该只能在Linux跑。。。。。建议用虚拟机，不要用云服务器，容易出错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinuxSuRen/api-testing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LinuxSuRen/api-testing] Support the execution records (Issue #345)





 
您好，我想问下这个项目在windows下可以编译吗？以及怎么编译呀？使用go build?

**Comment by LinuxSuRen** [comment]
Go 是支持在主流平台上运行、编译的，同时也支持跨平台编译（例如：在 Windows 上编译出 Linux 的可执行文件）。对于后端部分，最简单的就是把 Go 安装好后，在根目录执行：`go build`。

**Comment by Ink-33** [comment]
如果安装了`Make for Windows`，可以尝试使用`make build`进行编译。

**Comment by hahahashen** [comment]
谢谢大家的回答！我想问下这个社区有官方的交流群吗

**Comment by LinuxSuRen** [comment]
> 谢谢大家的回答！我想问下这个社区有官方的交流群吗

建议通过 issue 或 discussion 交流，方便信息的归档、搜索，也能避免 IM 中低质量的交流。当然，不排除跟进后续的发展有变化。

**Comment by LinuxSuRen** [comment]
hi All, In order to make all the potential students (or contributors) know more about this project. I just booked an online meeting for it. Please feel free to put this on you calendar and join us. And I highly recommend you prepare some questions. I will record the meeting, then upload it to [Bilibili](https://space.bilibili.com/433584098). See you there.

https://meeting.tencent.com/dm/z6sRTjC66Mh4

**Comment by kinue00** [comment]
导师你好，我是研二学生，有开发简单网页（React, Express, MongoDB）的经验，比较熟悉Postman。          
对这个项目很感兴趣，目前在自学Go和Vue，希望有机会能出一份力。🫡

**Comment by LinuxSuRen** [comment]
@kinue00 欢迎，项目报名还有段时间，可以借这段时间抓紧练习下 Go 和 Vue，尤其是参与下 good first issue 来熟悉项目。

**Comment by wt-goodluck** [comment]
导师你好，我是大二学生，了解go  gin  gorm  grpc ,希望可以为这个开源项目做出贡献

**Comment by LinuxSuRen** [comment]
hi @wt-goodluck ，首先感谢您关注这个项目，也欢迎积极参与进来。可以按照这个 issue 里给出的建议熟悉下同类产品、源码、good-first-issue。

> 看到您也发邮件给我了，就在这里一并回复了。如果有其他具体问题欢迎随时通过邮件、issue 沟通

**Comment by LinuxSuRen** [comment]
hi All, I will host the second meeting for those interested in this project.

Date: 2024/5/25 20:00
Link: https://meeting.tencent.com/dm/WiI7vwyzPSkf
Record: TODO

I'll answer any potential questions related to this project.

**Comment by hellorealworld1** [comment]
导师您好，我是大三学生，系统学习过前端开发,自学过后端开发，熟悉的预言是js和java,熟悉的框架有Vue、Express、SSM，有使用uniapp做过跨平台软件，同时也会使用postman、apifox等工具，不好意思关注开源之夏的时间有点晚，现在和您联系还来得及吗

**Comment by LinuxSuRen** [comment]
hi @hellorealworld1 ，感谢您对项目的关注，官方给出的报名截止日期为 6月4日。感兴趣的话，可以抓紧翻阅下当前 issue 中给出的相关信息，包括：建议、两次的会议记录等等。有一些同学已经通过 [good-first-issue](https://github.com/LinuxSuRen/api-testing/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) 对项目代码结构有了一定了解，这也是非常好的一个起点，加油。

> 看到您也给我发过邮件，就在此一并回复了。如果还有其他任何疑问、问题，都可以在相关渠道进行交流。

**Comment by bugoutianzhen123** [comment]
导师你好，我是大一学生，能够用go独立搭建一个后端项目，关注的比较晚，现在正在了解项目，希望来得及

**Comment by LinuxSuRen** [comment]
@bugoutianzhen123 同学您好，感谢您对项目的关注，只要是在官方截止报名之前能完成报名都有机会的。但考虑到时间确实比较紧张了。如果想要报名的话，这几天最好能多花点时间了解这个 issue 中相关的信息。

**Comment by LinuxSuRen** [comment]
本次开源之夏议题收到 6 份申请，我们会尽量详细地根据给出的信息（设计+项目参与情况等）来给出排序。再次感谢各位同学对项目的关注。

**Comment by LinuxSuRen** [comment]
截止目前为止，收到 9 位同学的邮件咨询，11 位同学提交的 PR 有合并，其中有位同学提交了 6 个 PR。有两次在线会议沟通，录屏播放量累计 233 次。

另外，大部分同学有通过 issue、邮件沟通、交流。

希望每一位同学都能匹配到自己感兴趣的项目，如果万一有没匹配成功的，也非常欢迎持续关注、参与到我们这个项目当中来。走出校门之前，有丰富、长期参与开源项目的经历，相信能够给你就业之路添加一抹亮。

**Comment by LinuxSuRen** [comment]
项目正式开始，第一次会议：

* 会议时间：2024/07/02 20:15-22:15
* 会议链接：https://meeting.tencent.com/dm/JBZTq1iBNJ7r

**Comment by SamYSF** [comment]
### **Milestone:**
- [ ]  初步实现前端页面。 (2 week 7.8-7.22)
- [ ] 完成各项功能的定义与实现。 (2.5 week 7.22-8.9 )
- [ ] 完善测试、开发模块中存在问题 (1 week 8.9-8.16 )

**Comment by LinuxSuRen** [comment]
@SamYSF 建议以上每个阶段至少提交一个 PR，最后一个大概率可能会有多个。另外，如果要先实现前端的话，需要考虑下有个开关来隐藏（显示）新功能，等到功能完全可用再去掉开关。

**Comment by LinuxSuRen** [comment]
![image](https://github.com/user-attachments/assets/4ca1c3ff-74d2-42e5-9109-e2e879cb36f6)

这里需要调整下，对于 ORM 以外的插件是不支持执行历史的，需要把相应的按钮隐藏了。

**Comment by LinuxSuRen** [comment]
![image](https://github.com/user-attachments/assets/98f08aaa-b7ca-41a1-b41d-ceab586b55cd)
![image](https://github.com/user-attachments/assets/60ff85b0-4998-4daa-8f26-e27c8611bd72)

这两处也可以考虑优化下

**Comment by LinuxSuRen** [comment]
恭喜🎉 @SamYSF 顺利完成开源之夏的活动
。

**Comment by SamYSF** [comment]
> 恭喜🎉 @SamYSF 顺利完成开源之夏的活动。

感谢 Rick 哥活动期间的指导。我收获很大，期待以后能参与更多开源活动。
