### ISSUE TITLE
Create a serviceMonitor in the helm chart

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#358]
We need the `ServiceMonitor` to expose the Promethus metrics. Please feel free to put it into https://github.com/LinuxSuRen/api-testing/tree/master/helm/api-testing/templates , and don't forget the compaitble.

See also https://stackoverflow.com/questions/52991038/how-to-create-a-servicemonitor-for-prometheus-operator

**Comment by n3A87** [comment]
hello, I would like to have a try！

**Comment by LinuxSuRen** [comment]
This issue is not difficult, but you need to setup a Kubernetes environment. You can do via the following ways:

* [Kind](https://kind.sigs.k8s.io/docs/user/quick-start/)
* [k3d](https://github.com/k3d-io/k3d/)
* [miniKube](https://minikube.sigs.k8s.io/docs/start/)
* [kubekey](https://github.com/kubesphere/kubekey)
* https://labs.play-with-k8s.com/

then, you need to install Promethus and [api-testing](https://linuxsuren.github.io/api-testing/helm.html)

**Comment by LinuxSuRen** [comment]
hi @n3A87 I will unassign this issue due to no response for a long time. But please let me know if you are still interested in it.

**Comment by n3A87** [comment]
> hi @n3A87 I will unassign this issue due to no response for a long time. But please let me know if you are still interested in it.

Thank you for your patience. Given my current circumstances, it's best to unassign me from the issue. I appreciate your understanding, and I'm open to future opportunities that fit better with my schedule.
