### ISSUE TITLE
Add the cookie setting for Golang code generator

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#360]
The [cookie setting](https://github.com/LinuxSuRen/api-testing/pull/355) is a new feature, but it is not been implemented in the Golang code generator. See also the following screenshots:

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/ccd4b4a5-7a6c-489e-85f7-04446df8469a)
![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/3aa2d0cb-55f4-468d-8908-83e402ba34b7)

you might need to update the following files:

* https://github.com/LinuxSuRen/api-testing/blob/master/pkg/generator/data/main.go.tpl
* https://github.com/LinuxSuRen/api-testing/blob/master/pkg/generator/golang_generator.go

## What you need to know
* Golang basic syntax
* Golang template
* Golang HTTP releated SDK

**Comment by BruceAko** [comment]
I'd like to try it. Please assign me, thanks.

**Comment by LinuxSuRen** [comment]
completed at https://github.com/LinuxSuRen/api-testing/pull/363
