### ISSUE TITLE
incorrect HTTP request body with the Golang code generator

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#364]
![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/31ef652e-37e4-4840-9959-fd861b86df2b)

See also the following files:

* https://github.com/LinuxSuRen/api-testing/blob/e05ff4b485e0c525ea7f78b4d653ddc230c5716e/pkg/generator/golang_generator.go
* https://github.com/LinuxSuRen/api-testing/blob/e05ff4b485e0c525ea7f78b4d653ddc230c5716e/pkg/generator/data/main.go.tpl

**Comment by Agility6** [comment]
我进行了简单的复现
<img width="1643" alt="image" src="https://github.com/LinuxSuRen/api-testing/assets/75616395/3f911e67-e58f-4e20-9345-06b1d0ee5403">
导致这个问题应该是因为在`golang_generator.go`使用了`html/template`进行解析
<img width="1162" alt="image" src="https://github.com/LinuxSuRen/api-testing/assets/75616395/83e6099f-7ad3-4b53-813b-333a6595e17b">

我的想法是，查看是否有方法在不改变`html/template`模式下进行特判。

**Comment by LinuxSuRen** [comment]
> 查看是否有方法在不改变html/template模式下进行特判

是否采用 `text/template` 也足够呢

> missing import "byes"

指的是缺少了对应的包引用，会导致编译失败

**Comment by Agility6** [comment]
I would like to try!

**Comment by LinuxSuRen** [comment]
Close because it is completed.
