### ISSUE TITLE
Support to generator Java code from a HTTP testCase

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#366]
Below is the Golang code generator.

* https://github.com/LinuxSuRen/api-testing/blob/e05ff4b485e0c525ea7f78b4d653ddc230c5716e/pkg/generator/golang_generator.go

Similarly, we could add the Java code generator. Please feel free to do some research to find out how to make a HTTP request in Java.

**Comment by Agility6** [comment]
I'm very interested in this issue, can I try it?🫣

**Comment by LinuxSuRen** [comment]
Good to hear it, go ahead.
