### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#370]
I got this error when I run a tests. I guess the target HTTP server response a big body.

This is API that I call `/server.Runner/RunTestCase`

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/dbec1b4e-7ebc-4622-89ac-87be04af7d43)
![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/b9c87df8-aa5a-42a7-ad48-d563ddedfa70)

## How to reproduce it
You can setup an easy HTTP server to response a big body.

## Background tech
You need to know the basic knowledge of `gRPC`. See also the following answer:

* https://stackoverflow.com/questions/55362342/grpc-received-message-larger-than-max-8653851-vs-4194304

**Comment by LinuxSuRen** [comment]
IMI, we need to check the size of HTTP resonse before sending it. Give it a friendly error message if the size is too big.

**Comment by acceleratorssr** [comment]
我想试试

**Comment by LinuxSuRen** [comment]
Welcome.
