### ISSUE TITLE
chore: license header style error.

### ISSUE THREAD

**Issue by yuluo-yx** [LinuxSuRen/api-testing#387]
*Description*:

license header, there seems to be a problem.

we can refer: 

1. https://github.com/apache/skywalking-go/blob/main/agent/core/compile.go
2. https://github.com/alibaba/higress/blob/main/cmd/higress/main.go
3. https://github.dev/envoyproxy/gateway/blob/main/internal/logging/log_test.go

**Comment by LinuxSuRen** [comment]
Golang supports multiple different comment styles. See also:

* https://github.com/kubernetes/kubernetes/blob/92270014e251674c799b9745ca7c8800be7979da/cmd/clicheck/check_cli_conventions.go

**Comment by LinuxSuRen** [comment]
IMO, both styles are ok.

**Comment by yuluo-yx** [comment]
> IMO, both styles are ok.

get. I will closed this issue.
