### ISSUE TITLE
Support to view the YAML on the testSuite page

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#393]
*Description*:
Want to view the YAML content of a test suite. As you can see below, users can view the YAML on the page.

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/028556e2-2b90-489f-a9b1-e63c18841405)

[optional *Relevant Links*:]
You might need to do the following things:

* Update [the proto file](https://github.com/LinuxSuRen/api-testing/blob/9156fb85a48308299adcc44f16e049b88c8f8f9e/pkg/server/server.proto), make it be able to return the YAML string
* Implement the logic
* Run command `make grpc grpc-gw` to generate codes
* Update the relevant pages

**Comment by LinuxSuRen** [comment]
Please let me know if you need any kinds of help.

**Comment by SamYSF** [comment]
I notice that this user's fork has not been updated for a long time and may not continue to complete this Issue.Would it be acceptable for me to proceed with this Issue?

**Comment by LinuxSuRen** [comment]
Sure. Please go ahead.

**Comment by SamYSF** [comment]
Now I have implemented view YAML under local storage, do I need to submit a PR first? Or continue implementing other storage methods?
<img width="612" alt="example" src="https://github.com/LinuxSuRen/api-testing/assets/98792230/691db584-ed28-464a-b05a-c74a76e2303b">

**Comment by LinuxSuRen** [comment]
Good job. You can put the YAML into `Codemirror`.

See also https://github.com/LinuxSuRen/api-testing/blob/0d481b31ab066f0dad201537d7cfc9bfd0942e17/console/atest-ui/src/views/TestCase.vue#L764C12-L764C23

> other storage methods

I didn't understand your point. I think this feature allows users to view or download the YAML file. We don't need to store it in a database or somewhere. So you can submit your PR.

**Comment by SamYSF** [comment]
> I didn't understand your point. I think this feature allows users to view or download the YAML file. We don't need to store it in a database or somewhere. So you can submit your PR.

The YAML being viewed originate from the current Suite and is stored in a local YAML file.

**Comment by LinuxSuRen** [comment]
How did you get the YAML string? Convert it to the front-end with js or backend. I prefer getting it from the backend. The front-end only responsible for showing the content.

The test suite might be stored in a YAML file or a database, s3 .etc.

**Comment by LinuxSuRen** [comment]
Sure. Please do it.
