### ISSUE TITLE
refactor: refactor API Testing frontend

### ISSUE THREAD

**Issue by yuluo-yx** [LinuxSuRen/api-testing#416]
## Refactor API Testing frontend

- [x] HTTP client component: fetch -> axios
- [x] Add page router : vue-router
- [x] Refactoring the front-end directory structure
- [ ] Logo design and inclusion in front-end pages
      ```
     discussion: https://github.com/LinuxSuRen/api-testing/discussions/169
      ```
- [x] Front-end page layout container refactoring
- [ ] Improve the theme switching function
     ```
        // src -> components -> HeaderComponents.vue
        <!-- todo：主题样式显示有误。 -->
        <!-- <li>
        <el-tooltip content="点击以切换主题" placement="bottom" effect="light">
        <el-switch
        v-model="darkOpt"
        inline-prompt
        :active-action-icon="Sunny"
        :inactive-action-icon="Moon"
        @click="setTheme()"
        />
        </el-tooltip>
        </li> -->
     ```

> The above fivepages are all under src -> views -> related folder, and the refactoring needs to be completed with related functional tests to make sure the function is normal.

- [x] Refactor welcome pages(Index pages)
- [x] Refactor Test pages
- [ ] Refactor Mock pages
- [ ] Refactor secrets pages
- [ ] Refactor store pages

## technology stack

[Axios](https://axios-http.com/)

[Element-plus](https://element-plus.org/zh-CN/#/zh-CN)

[Vue3](https://vuejs.org/)

[Vue-router](https://router.vuejs.org/zh/)

## The page effect is as follows:

![image](https://github.com/LinuxSuRen/api-testing/assets/77964041/7ce29c75-4f18-4b45-bd5c-aba283229434)

## PS Feel free to point out any guidance on color schemes and other aspects of the project.

**Comment by yuluo-yx** [comment]
Refactor Test pages @yuluo-yx

**Comment by LinuxSuRen** [comment]
It looks better.

**Comment by LinuxSuRen** [comment]
是否可以考虑把整体框架的重构完成了就提交 PR，每个页面的重构其他人也可以单独提交 PR

**Comment by LinuxSuRen** [comment]
Dark theme 的问题 @suoaiyisheng 在试着解决

**Comment by yuluo-yx** [comment]
> 是否可以考虑把整体框架的重构完成了就提交 PR，每个页面的重构其他人也可以单独提交 PR

是这样协同的，不过目前仓库地址在我的 github 空间里，也就是这个地址 https://github.com/yuluo-yx/api-testing/tree/0504-yuluo/front-api-re

**Comment by bugoutianzhen123** [comment]
![328023223-7ce29c75-4f18-4b45-bd5c-aba2832294341 - 副本](https://github.com/LinuxSuRen/api-testing/assets/148350506/4218c210-00de-4c5e-b677-7f5c326f4592)
是否可以让红箭头处的边框可以拖动到蓝线位置，在窗口化时可以获得更好的视觉体验
原来的前端会有窗口缩小后，页面元素未正确排列，导致文字重叠的问题
![Desktop Screenshot 2024 06 03 - 22 47 10 62](https://github.com/LinuxSuRen/api-testing/assets/148350506/f7046ca7-e124-4a6f-8781-4ca9f7281663)
