### ISSUE TITLE
Add description to the Docker image

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#419]
See the tips below

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/caa61d79-b253-4932-b46d-4975d5ef76bb)

You can add it to here

https://github.com/LinuxSuRen/api-testing/blob/fc085fe33752d323507a52f5b2940e7a363748eb/Dockerfile#L47

**Comment by yuluo-yx** [comment]
hi @LinuxSuRen Do you have any thoughts on the description? I can try.

**Comment by LinuxSuRen** [comment]
I did some research. It looks like it only supports a one-line description. Actually, we need a good one-line introduction to this project.

I use below on the [Docker hub](https://hub.docker.com/r/linuxsuren/api-testing) page.
```
This is an API testing tool that supports HTTP, gRPC, and GraphQL.
```
