### ISSUE TITLE
[Bug] When switching back and forth between the Test and Mock navigation tabs, it prompts "Oops, TypeError: xxx".

### ISSUE THREAD

**Issue by seanly** [LinuxSuRen/api-testing#427]
*Description*:
When switching between navigation tabs multiple times, the following error is consistently encountered.

<img width="650" alt="406099b43cbc9781798efbcdb864718" src="https://github.com/LinuxSuRen/api-testing/assets/232069/0338ecbe-37b3-489b-920b-c2ffb04447ff">

*Environment*:

![image](https://github.com/LinuxSuRen/api-testing/assets/232069/cb2b9d84-0bce-4400-849c-691c9d725963)

**Comment by nightingaleserver4** [comment]
Xxx
