### ISSUE TITLE
[Bug] frontpage no mock item

### ISSUE THREAD

**Issue by yuluo-yx** [LinuxSuRen/api-testing#441]
![image](https://github.com/LinuxSuRen/api-testing/assets/77964041/6e80bdae-cbad-4c2b-ae99-fba06f392cfc)

![image](https://github.com/LinuxSuRen/api-testing/assets/77964041/eda06302-e3a4-40a9-89f9-055a447a575a)

**Comment by LinuxSuRen** [comment]
How did you build it?

**Comment by yuluo-yx** [comment]
no. I download binary file from github release.

Rick ***@***.***>于2024年5月20日 周一08:57写道：

**Comment by LinuxSuRen** [comment]
https://github.com/LinuxSuRen/api-testing/pull/410 is not been released yet. You will see it in the next version or using the docker image `linuxsuren/api-testing:master`

**Comment by yuluo-yx** [comment]
and I run "atest server",  then open browser input localhost:8080

luo yu ***@***.***>于2024年5月20日 周一09:05写道：

**Comment by yuluo-yx** [comment]
got it. I will closed this issue. Thanks for your reply.

Rick ***@***.***>于2024年5月20日 周一09:07写道：
