### ISSUE TITLE
Got error when opening atest-desktop on Windows

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#444]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: api-testing should not crash, the expected value isn't
returned, etc.
As mentioned in the title.

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
Build the desktop package with the following command:

```shell
cd console/atest-desktop/
npm i
npm run package
```

then open it from `console/atest-desktop/out/atest-desktop-win32-x64/atest-desktop.exe`

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.
![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/83385546-bb36-4476-88d4-75c9874413f2)

You can pay attention to this line https://github.com/LinuxSuRen/api-testing/blob/b40eea5afaca9e873ece02e54df652d802af1cda/console/atest-desktop/main.js#L18
*Environment*:
>Include the environment like api-testing version, os version and so on.

*Logs*:
>Include the access logs and the api-testing logs.
> 
![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/95631bd9-0d46-41af-a94e-6257fc999f40)

**Comment by DWJ-Squirtle** [comment]
kindly to ask if there is somebody working for this issue?if not,i'm glad to undertake it

**Comment by LinuxSuRen** [comment]
Thanks for your attention. Please go ahead.

/assign @DWJ-Squirtle

**Comment by DWJ-Squirtle** [comment]
I see, the issue seems to be related to the line of code ‘app.dock.setIcon(path.join(__dirname, "/api-testing.png"))’. This code is specific to macOS systems and cannot be used on Windows.

**Comment by LinuxSuRen** [comment]
It should be.

**Comment by DWJ-Squirtle** [comment]
> It should be.

Simply commenting out that line of code should not affect the operation, but the exe file still cannot be started and there is no prompt. I want to know where the log file is so I can further check the problem. I hope you can tell me.

**Comment by LinuxSuRen** [comment]
You can add a condition check. For instance: `process.platform === 'darwin'`. You can find the log file below:

`log.transports.file.resolvePathFn = () => path.join(atestHome, 'log.log');`
