### ISSUE TITLE
Support to set the timeout of the git extension

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#470]
As described below:

https://github.com/go-git/go-git/blob/c4390a64249356c285c069c6cc833e81539a55d8/_examples/custom_http/main.go

We can add an option to set the timeout of cloning git repositories. You might need to update the following code lines:

https://github.com/LinuxSuRen/atest-ext-store-git/blob/f72097a3be070e36230247e6fd4aaacbae878b80/pkg/server.go#L271

**Comment by SamYSF** [comment]
I want to try this issue, "add an option to set the timeout" mean the user can choose to add or not to add?

**Comment by LinuxSuRen** [comment]
For the backend, it can take the `timeout` option from context. See also https://github.com/LinuxSuRen/atest-ext-store-git/blob/f72097a3be070e36230247e6fd4aaacbae878b80/pkg/server.go#L285

For the frontend, users can add the extra config item:

![image](https://github.com/LinuxSuRen/api-testing/assets/1450685/5a5d0755-45d9-4de2-b77e-89f68255b580)
