### ISSUE TITLE
Command "atest service action" is not support in CentOS

### ISSUE THREAD

**Issue by yJunS** [LinuxSuRen/api-testing#63]
OS: CentOS 7.9
Version: 0.0.11
Install Mode: Install it via [hd](https://github.com/LinuxSuRen/http-downloader)

I try the command `atest service --action start|stop|restart|status`, and print the error information. Like this:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/20575981/236856837-7c5d857f-1547-477c-a059-732918f032aa.png">
Then I see the code in the programs is `systemctl start atest`, I tried to run it, and the result is :
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/20575981/236857882-5a8649fa-e05e-4dfd-beb5-2de19e7c80f6.png">

**Comment by yJunS** [comment]
What I tried was to install first, then start, but it's a tip error, like this:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/20575981/236968608-e0176cd3-55de-4071-a14d-4783dfac7d0d.png">

**Comment by LinuxSuRen** [comment]
Thanks for the feedback. Please help to see if the file `/lib/systemd/system/atest.service` exists and good.

See also the following relvant code lines:

https://github.com/LinuxSuRen/api-testing/blob/bb745044bc3dea530b2d449c18bc653accb84ba5/cmd/service.go#LL25C56-L25C89

**Comment by LinuxSuRen** [comment]
Good job! @wongearl

**Comment by yJunS** [comment]
Can we add `/usr/bin/env` in front of this path to make the system environment effective? I tried the method is ok. If agree with this, I'll pull request for this.

**Comment by LinuxSuRen** [comment]
Please go ahead if it works well.
