### ISSUE TITLE
Feature: Request for Executing an API Request after Another API Request and Supporting Delayed Execution

### ISSUE THREAD

**Issue by rockburning** [LinuxSuRen/api-testing#68]
大佬您好：                                                                                                                                                                                                 
  我希望请求在特定的API端点上增加延迟功能，某个api 在另外一个api之后进行，并运行延迟一段时间（比如某个 api先create,然后多一段时间执行另外一个api请求）。这个功能将极大地提升处理API调用的灵活性和控制性。

目前，在向API端点发送请求后需要引入延迟，以模拟特定情景或确保与外部系统的同步。然而，现有的实现缺乏将这种延迟纳入考虑的能力。

提议的解决方案是扩展API测试框架，以在每个API端点上包含可配置的延迟选项。此外，支持后续执行操作将非常有益，允许用户定义在请求发送后立即执行的特定任务。

整合这些功能将使用户能够创建更全面的测试场景，包括涉及延迟和后续操作的情景，最终提高框架的整体测试能力。

感谢您考虑这个请求。比如 增加after:xxApi;  delay;1minute; 表示该api 在xxApi 1分钟后执行

**Comment by LinuxSuRen** [comment]
@rockburning 感谢反馈需求。

关于增加延迟，如果增加一个全局的延迟配置，这个延迟是一个动态的延迟范围，例如：2~5s 之间。也就是说，在每两个请求之间动态延迟 2~5s。这样的话，就不再需要为每一个请求单独配置延迟了。而且，还可以通过命令行或其他方式进行控制这个参数。当然，这个方案不一定能完全满足您的诉求，但如果您感觉差不多的话，我可以优先安装这个来实现。

第二点，是关于 API 请求之间的先后顺序的问题。目前的实现方式是，通过值引用的方式 + 编写顺序来确保正确的顺序。假设，有 A、B 两个请求，A 在 B 前面，B 引用 A 的 response。参考示例如 https://github.com/LinuxSuRen/api-testing/blob/2a3c59456265d2b044aa8df31636a1b053505867/sample/testsuite-gitlab.yaml#L17

同样，对于 API 顺序的问题，也可能无法完全满足您的诉求。但您可以看是否可以作为相对临时的方案来用。因为，考虑到指定顺序的话，也有不少的弊端，例如：关系复杂、可能会导致循环调用等。当然，实际上，可以借助 YAML 的数据关系生成一个测试用例网络拓扑图之类的，方便查看用例之间的关系。

我会持续改进相关功能，尽量提供相对更好的、更简单的 feature 给到用户。再次感谢！

**Comment by rockburning** [comment]
关于第一点：个人认为，增加全局配置的话，可能会导致测试时间过长，如果实现方便的话，个人感觉对于A,B两个接口，B延迟A接口2-5s,不知道方便实现不；您可以综合考虑一下；
第二点的话；也可以

**Comment by rockburning** [comment]
感谢

**Comment by LinuxSuRen** [comment]
实现这个需求本身不难，我再想一下如何扩展，避免后续增加额外功能导致使用变得复杂

**Comment by LinuxSuRen** [comment]
@rockburning 不知道您有没有尝试用 https://github.com/LinuxSuRen/api-testing/pull/69 提供的实现，如果没啥问题的话，我本周会合并、发版。
