### ISSUE TITLE
Support gRPC test cases

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/api-testing#81]
gRPC is a very popular protocol. It would be great if we could have this feature. Please feel free to see also the following ideas if you're interested in it:

* Support all common feature of gRPC
* CLI and server side supports both needed
* VSCode extension support will be optinal
* Have a good compitable with the current YAML specification
* Docuemntation output

## Online Meetings
* [GLCC API Testing ~ gRPC 课题讨论会-1](https://www.bilibili.com/video/BV1xj411U7Wm/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925)
* [GLCC 活动中 API-Testing 项目的第二次沟通](https://www.bilibili.com/video/BV1hp4y1g7Ao/?share_source=copy_web&vd_source=1e8d9e70686a4845fa44f8d3f5ff7925)

**Comment by LinuxSuRen** [comment]
We only accept this proposal from [GLCC 2023](https://www.gitlink.org.cn/glcc/2023/subjects/detail/656). Please feel free to see it if you're interested in it. By the way, only students could take it acorrding to the GLCC official rule。

**Comment by kaizhong2021** [comment]
I have submitted my application.

**Comment by LinuxSuRen** [comment]
hi @kaizhong2021 Please double check your application status. I didn't see it.

**Comment by LinuxSuRen** [comment]
See also [the Twitter thread](https://twitter.com/LinuxSuRen/status/1669149705140305922) of this topic.

**Comment by LinuxSuRen** [comment]
Finally, @Ink-33 will take this issue. Please see the detail from https://github.com/LinuxSuRen/api-testing/pull/111

**Comment by LinuxSuRen** [comment]
hi @Ink-33 , I suggest we take an initial meeting to talk about this proposal. There are some potential outcomes from the meeting.

* A discussed development plan which should contain timeline and keypoints.
* The later meetings arrangment.
* Any others.

Please pick up a time slot in [Calendly](https://calendly.com/d/z7b-qj7-t7w/api-testing-glcc-initial-meeting).

**Comment by Ink-33** [comment]
> hi @Ink-33 , I suggest we take an initial meeting to talk about this proposal. There are some potential outcomes from the meeting.
> 
> * A discussed development plan which should contain timeline and keypoints.
> * The later meetings arrangment.
> * Any others.
> 
> Please pick up a time slot in [Calendly](https://calendly.com/d/z7b-qj7-t7w/api-testing-glcc-initial-meeting).

Thanks. I have picked a proper time slot through the calendly.

**Comment by LinuxSuRen** [comment]
hi @Ink-33 Please feel free to see [GRPC Server Reflection Protocol](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md). In my view, it could help discover the gRPC service.

By the way, it would be more clear if it's confortable for you to put the date on your milestone list.

**Comment by LinuxSuRen** [comment]
I found another great tool [grpcurl](https://github.com/fullstorydev/grpcurl#installation). I'm wondering if it's possible to reuse it.

**Comment by Ink-33** [comment]
> hi @Ink-33 Please feel free to see [GRPC Server Reflection Protocol](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md). In my view, it could help discover the gRPC service.
> 
> By the way, it would be more clear if it's confortable for you to put the date on your milestone list.

I will update it later. 

There is something emergency that I have to put off the whole project for about 2 week, so the start time of first step may be set as the middle of this mouth.

**Comment by LinuxSuRen** [comment]
> There is something emergency that I have to put off the whole project for about 2 week, so the start time of first step may be set as the middle of this mouth.

Sure. No problem. I could check the point if there is a clear timeline.

**Comment by Ink-33** [comment]
> I found another great tool [grpcurl](https://github.com/fullstorydev/grpcurl#installation). I'm wondering if it's possible to reuse it.

I see. That project have done a lot of great work. I will try to reuse it.

**Comment by LinuxSuRen** [comment]
I find another type of RPC. [BRPC](https://gitee.com/baidu/BRPC) was created by Baidu. We could try to support it after GLCC.

**Comment by LinuxSuRen** [comment]
hi @Ink-33 there are still some work need to do for this issue:

* The unit tests are not enough
* The server side which means the gRPC server
* Document about how to use

**Comment by LinuxSuRen** [comment]
hi @Ink-33 Congrats! You did it. Thanks for your time on this project. Hopefully you learned something in this summer. And I'm looking forward to having more collaboration in this project or others.

![1697080129410](https://github.com/LinuxSuRen/api-testing/assets/1450685/bc40cbca-1b69-4c98-80c1-aef2998fbe40)

https://www.gitlink.org.cn/glcc/2023/result
